Fix build issue with MSVC
The error output is

  error C2398: Element '2': conversion from 'int' to 'const std::basic_string_view<char,std::char_traits<char>>::size_type'
  requires a narrowing conversion