Fix build with -Werror=unused-parameter and --disable-spreadsheet-model
It addresses

> orcus_json_cli_map.cpp: In function ‘void orcus::detail::map_to_sheets_and_dump(const orcus::file_content&, orcus::detail::cmd_params&)’:
> orcus_json_cli_map.cpp:47:49: error: unused parameter ‘content’ [-Werror=unused-parameter]
>    47 | void map_to_sheets_and_dump(const file_content& content, cmd_params& params)
>       |                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~
> orcus_json_cli_map.cpp:47:70: error: unused parameter ‘params’ [-Werror=unused-parameter]
>    47 | void map_to_sheets_and_dump(const file_content& content, cmd_params& params)
>       |

and

> python.cpp:99:6: error: ‘bool orcus::python::{anonymous}::add_type_to_module(PyObject*, PyTypeObject*, const char*)’ defined but not used [-Werror=unused-function]
>    99 | bool add_type_to_module(PyObject* m, PyTypeObject* typeobj, const char* type_name)
>       |