Remove unused parameter
> json_subtree_1.cpp:110:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
>   110 | int main(int argc, char** argv)
>       |          ~~~~^~~~
> json_subtree_1.cpp:110:27: error: unused parameter ‘argv’ [-Werror=unused-parameter]
>   110 | int main(int argc, char** argv)
>       |                    ~~~~~~~^~~~