Remove unused parameter warning
> xlsx_pivot_context.cpp:864:29: error: unused parameter 'parent' [-Werror=unused-parameter]
>   864 |     const xml_token_pair_t& parent, const xml_token_attrs_t& attrs)
>       |     ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~