Fix build issue with MSVC when building with mdds 3.2.0
This should fix the following build error:

  (...)\include\mdds-3.0\mdds\segment_tree.hpp(59,87): error C2676: binary '<': 'orcus::gnumeric_value_format_segment' does not define this operator or a conversion to a type acceptable to the predefined operator

Also mark the equality operator noexcept.